#
# This pipeline needs the following tasks from Tekton Hub
#   - git-clone
#   - flake8
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
      description: A workspace for the pipeline to store cloned files and other shared data
  params:
    - name: repo-url
      description: The URL of the repository to clone
      type: string
    - name: branch
      description: The branch to clone from the repository
      type: string
      default: main
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      runAfter:
        - init
    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: flake8
        kind: Task
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value: ["--count","--max-complexity=10","--max-line-length=127","--statistics"]
      runAfter:
        - clone
